from langchain.text_splitter import CharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader


loader = PyPDFLoader('./Data/RP1.pdf')

docs = loader.lazy_load()

splitter=CharacterTextSplitter(
    chunk_size = 100,
    chunk_overlap=0,  # for rag based applications --> 10-20 % of chunk_size
    separator=''      # if separator not provided then you might get the whole document instead of the chunk
)
 

res = splitter.split_documents(docs)

print('type of res',type(res))

print('len fo res',len(res))
print()
print(res[0])

print(res[1])









# from langchain.text_splitter import CharacterTextSplitter

# text = '''
# To  address  these  shortcomings,  we  present  Prepmania—a  computer-based  mock  interview  platform,  built  using  Next.js  and  a 
# modern  web  stack.  The  platform  delivers role-specific,  user-profile-based  interview  questions and  evaluates  verbal and non-verbal 
# cues  through  multimodal  analysis,  including  body  language,  tone,  and  speech  intelligibility.  These  behavioral  signals  help  deliver 
# objective, real-time feedback to candidates, enabling them to identify improvement areas and enhance their interview readiness. 
# Prepmania does this by using a very detailed feedback dashboard that compares user responses with the best responses generated by 
# AI  and  displays  progress  in  graphs  and  reports.  This  paper  captures  the  system  design,  development  process,  and  initial  user 
# response for Prepmania. The findings set the potential of AI and web technologies to transform the interview preparation process to 
# make it more streamlined, personalized, and evidence-based.
# '''

# splitter = CharacterTextSplitter(
#     chunk_size=100,
#     chunk_overlap=0
# )

# res = splitter.split_text(text)

# print(res)
# print(type(res))
# print(res[0])